title: "[Software Suggestion] "
labels: ["software", "suggestion"]
body:
  - type: markdown
    attributes:
      value: |
        # Software Information

  - type: markdown
    attributes:
      value: |
        ## Required

  - type: input
    id: software-name
    attributes:
      label: Software name
      placeholder: Software Name
    validations:
      required: true

  - type: input
    id: website
    attributes:
      label: Website
      placeholder: http://softwareweb.com/home
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Recommended

  - type: textarea
    id: about
    attributes:
      label: About
      description: Very short software description.
      placeholder: Very short software description.
      render: markdown   # Opcional, para que soporte formato si el usuario lo usa
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### Favicon URLs

  - type: input
    id: favicon-light
    attributes:
      label: Light
      description: URL to the light mode favicon (optional)
      placeholder: http://softwarename.com/favicon.ico
    validations:
      required: false

  - type: input
    id: favicon-dark
    attributes:
      label: Dark
      description: URL to the dark mode favicon (optional)
      placeholder: http://softwareweb.com/favicon_dark.ico
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### Operating Systems

        **Important**: For this list, the software **must** support at least Windows, macOS and Linux natively.  
        Please check **Windows**, **MacOS** and **Linux** below (they are required for inclusion).

  - type: checkboxes
    id: operating-systems
    attributes:
      label: Supported Operating Systems
      options:
        - label: Windows
        - label: MacOS
        - label: Linux
        - label: Android
        - label: iOS
        - label: ChromeOS
        - label: FreeBSD
      validations:
        required: true   # Obliga a seleccionar al menos uno (pero no fuerza los específicos)
