name: Software Submission
description: Add new software information to the project
title: "[Software]: "
body:
  - type: markdown
    attributes:
      value: "### Please fill out the software details below."
  - type: input
    id: software_name
    attributes:
      label: "Software Name"
    validations:
      required: true
  - type: input
    id: website
    attributes:
      label: "Website URL"
    validations:
      required: true
  - type: textarea
    id: about
    attributes:
      label: "About"
  - type: checkboxes
    id: os
    attributes:
      label: "Operating System"
      options:
        - label: Windows
        - label: MacOS
        - label: Linux
        - label: Android
        - label: iOS
