title: "[Software Suggestion] "
labels: ["software", "suggestion"]
body:
  - type: markdown
    attributes:
      value: |
        # Software Information

  - type: markdown
    attributes:
      value: |
        ## Required

  - type: input
    id: software-name
    attributes:
      label: Software name
      placeholder: Software Name
    validations:
      required: true

  - type: input
    id: website
    attributes:
      label: Website
      placeholder: http://softwareweb.com/home
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Recommended

  - type: textarea
    id: about
    attributes:
      label: About
      description: Very short software description.
      placeholder: Very short software description.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### Favicon URLs

  - type: input
    id: favicon-light
    attributes:
      label: Light
      description: URL to the light mode favicon (optional)
      placeholder: http://softwarename.com/favicon.ico
    validations:
      required: false

  - type: input
    id: favicon-dark
    attributes:
      label: Dark
      description: URL to the dark mode favicon (optional)
      placeholder: http://softwareweb.com/favicon_dark.ico
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### Operating Systems

        **Important for inclusion**  
        This list focuses on native cross-platform software that supports **at least Windows, macOS, and Linux**.  
        Please make sure to check **Windows**, **MacOS**, and **Linux** below. Suggestions without these three will likely be rejected.

  - type: checkboxes
    id: operating-systems
    attributes:
      label: Supported Operating Systems
      options:
        - label: Windows
        - label: MacOS
        - label: Linux
        - label: Android
        - label: iOS
        - label: ChromeOS
        - label: FreeBSD
