name: Software Submission
description: Add new software information
title: "[Software]: "
body:
  - type: markdown
    attributes:
      value: "### Software Information"
  - type: input
    id: software_name
    attributes:
      label: Software Name
    validations:
      required: true
  - type: input
    id: website
    attributes:
      label: Website URL
    validations:
      required: true
  - type: textarea
    id: about
    attributes:
      label: About
  - type: input
    id: favicon_light
    attributes:
      label: Favicon URL (Light)
  - type: input
    id: favicon_dark
    attributes:
      label: Favicon URL (Dark)
  - type: checkboxes
    id: os
    attributes:
      label: Operating System
      options:
        - label: Windows
        - label: MacOS
        - label: Linux
        - label: Android
        - label: iOS
        - label: ChromeOS
        - label: FreeBSD
