name: Software Submission
description: Form to add new software info
title: "[Software]: "
labels: ["new-software"]
category: New Software
body:
  - type: markdown
    attributes:
      value: |
        # Software Information
        Complete the fields below to contribute.
  - type: input
    id: name
    attributes:
      label: "Software Name"
    validations:
      required: true
  - type: input
    id: web
    attributes:
      label: "Website URL"
    validations:
      required: true
  - type: textarea
    id: about
    attributes:
      label: "About"
      description: "Short description"
  - type: input
    id: fav_light
    attributes:
      label: "Favicon Light"
  - type: input
    id: fav_dark
    attributes:
      label: "Favicon Dark"
  - type: checkboxes
    id: os
    attributes:
      label: "Operating System"
      options:
        - label: Windows
        - label: MacOS
        - label: Linux
        - label: Android
        - label: iOS
        - label: ChromeOS
        - label: FreeBSD
